SMDX_METADATA_CONCEPTS: SDMX Metadata Concepts
INDICATOR_NUMBER: 'Indicator: %number'
DOWNLOAD_PDF: Download PDF
REVISION_HISTORY: Revision history
STATISTICS: Translation statistics
ALL_METADATA: All metadata
