SMDX_METADATA_CONCEPTS: Conceptos de metadatos SDMX
INDICATOR_NUMBER: 'Indicador: %number'
DOWNLOAD_PDF: Descargar PDF
REVISION_HISTORY: 'Historial de revisión'
STATISTICS: 'Estadísticas de traducción'
ALL_METADATA: Todos los metadatos
