SMDX_METADATA_CONCEPTS: Понятия SDMX метаданных
INDICATOR_NUMBER: 'Показатель: % число'
DOWNLOAD_PDF: Скачать PDF
REVISION_HISTORY: 'Лист регистраций изменений'
STATISTICS: 'Статистика переводов'
ALL_METADATA: Все метаданные
