SMDX_METADATA_CONCEPTS: Concepts de métadonnées SDMX
INDICATOR_NUMBER: 'Indicateur : %number'
DOWNLOAD_PDF: Télécharger PDF
REVISION_HISTORY: 'Historique de révision'
STATISTICS: Statistiques de traduction
ALL_METADATA: Toutes les métadonnées
